<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Category Report</title>
</head>
<body>
<div style="margin-bottom:25px;"><strong>Report generated by: {{ $username }}</strong></div>
<table style="border-collapse: collapse;">
    <thead>
    <tr>
        <th style="border-bottom:2pt solid black;">
            <strong>ID</strong>
        </th>
        <th style="border-bottom:2pt solid black;">
            <strong>Name</strong>
        </th>
        <th style="border-bottom:2pt solid black;">
            <strong>Status</strong>
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach ($categories as $category)
        <tr>
            <td style="border-bottom:1pt solid black;">
                {{$category->id}}
            </td>
            <td style="border-bottom:1pt solid black;">
                {{$category->name}}
            </td>
            <td style="border-bottom:1pt solid black;">
                {{ $category->status ? 'Active' : 'InAvtive'}}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
</body>
</html>
